version: "3"
services:
  # Service a 
  colaborator:
    build:
      context: ./services/colaborator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  # Service b
  character:
    build:
      context: ./services/character
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
